"""Schema test for run_model.py output format.

Validates the output JSON schema against a committed fixture generated by:
  python scripts/run_model.py --model openai-community/gpt2 --output smoke_fixture_gpt2.json \
    --ex-dim 10 --batch-size 4 --layers-per-pass 6 --attn-impl sdpa --seeds 2 --skip-c4 --max-docs 200

No network access, no model download, no GPU required.
"""

import json
from pathlib import Path

import pytest

RESULTS_DIR = Path(__file__).resolve().parent.parent / "results"
FIXTURE_FILE = "smoke_fixture_gpt2.json"


@pytest.fixture(scope="module")
def smoke_results():
    """Load committed fixture."""
    path = RESULTS_DIR / FIXTURE_FILE
    assert path.exists(), (
        f"Fixture missing: {path}. Regenerate with: python scripts/run_model.py --model openai-community/gpt2 --output {FIXTURE_FILE} --ex-dim 10 --seeds 2 --skip-c4 --max-docs 200"
    )
    return json.loads(path.read_text())


def test_model_metadata(smoke_results):
    assert smoke_results["model"] == "openai-community/gpt2"
    assert smoke_results["n_layers"] == 12
    assert smoke_results["hidden_dim"] == 768


def test_partial_corr_schema(smoke_results):
    pc = smoke_results["partial_corr"]
    assert "mean" in pc
    assert "per_seed" in pc
    assert len(pc["per_seed"]) == pc["n_seeds"]
    assert all(isinstance(v, float) for v in pc["per_seed"])


def test_partial_corr_positive(smoke_results):
    assert smoke_results["partial_corr"]["mean"] > 0


def test_test_split_exists(smoke_results):
    tsc = smoke_results["test_split_comparison"]
    assert "mean" in tsc
    assert "per_seed" in tsc


def test_seed_agreement(smoke_results):
    sa = smoke_results["seed_agreement"]
    assert sa["mean"] > 0.5


def test_output_controlled(smoke_results):
    oc = smoke_results["output_controlled"]
    assert "mean" in oc
    assert "per_seed" in oc


def test_baselines(smoke_results):
    bl = smoke_results["baselines"]
    for key in ["ff_goodness", "active_ratio", "act_entropy", "activation_norm", "random_head"]:
        assert key in bl, f"Missing baseline: {key}"


def test_cross_domain(smoke_results):
    cd = smoke_results["cross_domain"]
    assert "wikitext" in cd
    # c4 keys absent when run with --skip-c4
    if "c4" in cd:
        assert "c4_within" in cd


def test_control_sensitivity(smoke_results):
    cs = smoke_results["control_sensitivity"]
    for key in ["none", "softmax_only", "standard", "plus_entropy", "nonlinear"]:
        assert key in cs, f"Missing control: {key}"
    assert cs["none"] > cs["standard"]


def test_flagging(smoke_results):
    fl = smoke_results["flagging_6a"]
    assert "n_tokens" in fl
    assert "summary" in fl
    assert "0.1" in fl["summary"]


def test_layer_profile(smoke_results):
    lp = smoke_results["layer_profile"]
    assert len(lp) == 12
    assert all(isinstance(v, float) for v in lp.values())
